// Arbitrum Sepolia Testnet deployment config
// Mirrors xlayer.ts structure — same mock contracts (MockXStock + OnStockVault)
// Contracts will be deployed via xlayer-contracts/scripts/deploy.js --network arbitrumSepolia

export const ARBITRUM_CONFIG = {
  chainId: 421614,
  rpc: 'https://sepolia-rollup.arbitrum.io/rpc',
  explorer: 'https://sepolia.arbiscan.io',
  gasToken: 'ETH',

  // Will be filled after deployment
  contracts: {
    usdc: '',    // MockUSDC address
    factory: '', // VaultFactory address
  },

  tokens: {} as Record<string, string>,  // symbol → token address
  vaults: {} as Record<string, string>,  // symbol → vault address

  // Same APY structure as X Layer
  apyBps: {
    TSLAx: 460, NVDAx: 460, SPYx: 420, AAPLx: 460,
    GOOGLx: 460, METAx: 460, COINx: 600, MSTRx: 600,
  } as Record<string, number>,
}

// Minimal ABIs — same as xlayer.ts
export const ARB_VAULT_ABI = [
  'function deposit(uint256 assets, address receiver) returns (uint256)',
  'function withdraw(uint256 assets, address receiver, address owner) returns (uint256)',
  'function redeem(uint256 shares, address receiver, address owner) returns (uint256)',
  'function balanceOf(address) view returns (uint256)',
  'function totalAssets() view returns (uint256)',
  'function totalSupply() view returns (uint256)',
  'function convertToShares(uint256 assets) view returns (uint256)',
  'function convertToAssets(uint256 shares) view returns (uint256)',
  'function asset() view returns (address)',
]

export const ARB_ERC20_ABI = [
  'function balanceOf(address) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function decimals() view returns (uint8)',
  'function mint(address to, uint256 amount)',
]

/**
 * Load deployment addresses from JSON file (generated by hardhat deploy script)
 */
export function loadArbitrumDeployment(): boolean {
  try {
    const fs = require('fs')
    const path = require('path')
    const deployFile = path.resolve(__dirname, '../../../xlayer-contracts/deployment-arbitrumSepolia.json')
    if (!fs.existsSync(deployFile)) {
      console.log('[Arbitrum] No deployment file found — Arbitrum routes disabled')
      return false
    }
    const data = JSON.parse(fs.readFileSync(deployFile, 'utf8'))
    ARBITRUM_CONFIG.contracts.usdc = data.usdc
    ARBITRUM_CONFIG.contracts.factory = data.factory
    ARBITRUM_CONFIG.tokens = data.tokens
    ARBITRUM_CONFIG.vaults = data.vaults
    console.log(`[Arbitrum] Loaded ${Object.keys(data.tokens).length} tokens from deployment`)
    return true
  } catch (e) {
    console.log('[Arbitrum] Failed to load deployment:', (e as Error).message)
    return false
  }
}
