[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onstock_vault = "Dp5XeudXm3dfSNnLLC6M8dPhDXd6nFmMX9SGNCTtGmKx"

[programs.devnet]
onstock_vault = "Dp5XeudXm3dfSNnLLC6M8dPhDXd6nFmMX9SGNCTtGmKx"

[programs.testnet]
onstock_vault = "Dp5XeudXm3dfSNnLLC6M8dPhDXd6nFmMX9SGNCTtGmKx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --require ts-node/register"
